/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


/**
 *
 * @author 5102011212
 */
public class ExecucaoShuttleRun extends javax.swing.JPanel {


    /**
     * Creates new form ExecutionShuttleRun
     */
    public ExecucaoShuttleRun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOnlineOffline = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbShuttleRun = new javax.swing.JTable();
        rbOnline = new javax.swing.JRadioButton();
        rbOffline = new javax.swing.JRadioButton();
        btIniciar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        tbShuttleRun.setModel(new visao.modelosComponentes.ShuttleRunTableModelOnline());
        tbShuttleRun.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(tbShuttleRun);

        bgOnlineOffline.add(rbOnline);
        rbOnline.setText("Online");

        bgOnlineOffline.add(rbOffline);
        rbOffline.setText("Offline");

        btIniciar.setText("Iniciar");

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);

        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbOnline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbOffline)
                        .addGap(26, 26, 26)
                        .addComponent(btIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir)
                        .addComponent(btSalvar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbOnline)
                        .addComponent(rbOffline)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOnlineOffline;
    public javax.swing.JButton btExcluir;
    public javax.swing.JButton btIniciar;
    public javax.swing.JButton btSalvar;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JRadioButton rbOffline;
    public javax.swing.JRadioButton rbOnline;
    public javax.swing.JTable tbShuttleRun;
    // End of variables declaration//GEN-END:variables

}
