/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Diego Heusser
 */
public class MenuPrincipal extends javax.swing.JFrame {


    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btInstituicao = new javax.swing.JButton();
        btAtleta = new javax.swing.JButton();
        btGrupo = new javax.swing.JButton();
        btAgenda = new javax.swing.JButton();
        btExecuta = new javax.swing.JButton();
        btProtocolos = new javax.swing.JButton();
        btRelatorios = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btPersonalizar = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Avalição Física para Badminton");
        setState(MAXIMIZED_BOTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btInstituicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/entidade.png"))); // NOI18N
        btInstituicao.setText("Institução");
        btInstituicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btInstituicao.setEnabled(false);
        btInstituicao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btInstituicao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btInstituicao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/a.png"))); // NOI18N
        btAtleta.setText("Atleta");
        btAtleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAtleta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btAtleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/Grupos.png"))); // NOI18N
        btGrupo.setText("Grupos");
        btGrupo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGrupo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGrupo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btGrupo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/agenda3.png"))); // NOI18N
        btAgenda.setText("Agenda");
        btAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAgenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btExecuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/executar.png"))); // NOI18N
        btExecuta.setText("Executar");
        btExecuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExecuta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExecuta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btExecuta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btProtocolos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/protocolos.png"))); // NOI18N
        btProtocolos.setText("Protocolos");
        btProtocolos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProtocolos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProtocolos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btProtocolos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/relatorio.png"))); // NOI18N
        btRelatorios.setText("Relatórios");
        btRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRelatorios.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btPersonalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/personalizar.png"))); // NOI18N
        btPersonalizar.setText("Personalizar");
        btPersonalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPersonalizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPersonalizar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btPersonalizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExecuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btProtocolos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btPersonalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInstituicao)
                    .addComponent(btAtleta)
                    .addComponent(btGrupo)
                    .addComponent(btAgenda)
                    .addComponent(btExecuta)
                    .addComponent(btProtocolos)
                    .addComponent(btRelatorios)
                    .addComponent(btSair)
                    .addComponent(btPersonalizar))
                .addContainerGap())
        );

        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAgenda;
    public javax.swing.JButton btAtleta;
    public javax.swing.JButton btExecuta;
    public javax.swing.JButton btGrupo;
    public javax.swing.JButton btInstituicao;
    public javax.swing.JButton btPersonalizar;
    public javax.swing.JButton btProtocolos;
    public javax.swing.JButton btRelatorios;
    public javax.swing.JButton btSair;
    public javax.swing.JPanel jPanel;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
