/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author 5102011212
 */
public class ProtShuttleRun extends javax.swing.JPanel {

    /**
     * Creates new form P20MetrosDeCorrida
     */
    public ProtShuttleRun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbLink = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Teste de 20 metros de corrida"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("<html>O teste de aptidão de multi – estágios, também conhecido como teste de 20 metros de corrida, bipe sinal entre outros, é hoje em dia um teste de aptidão aeróbica muito comum.\n<br><br><b>Descrição:</b>\n<br>Este teste envolve continuas corridas entre duas linhas de 20 metros separadas no tempo registrado dos bipes. Por este motivo o teste também é frequentemente chamado de  Teste do‘bipe’ ou ‘sinal’. O tempo entre os bipes diminui a cada minuto(nível). Existem diversas versões do teste, mas versão utilizada tem uma velocidade de corrida inicial de 8,5 km / h, e aumenta a 0,5 km / h a cada minuto.\n<br><br><b>Pontuação:</b>\n<br>A pontuação dos atletas é o nível e o número de  circuitos que alcançaram antes que eles foram incapazes de acompanhar a gravação. Essa pontuação pode ser convertida em uma pontuação equivalente VO2max utilizando a tabela que está no apêndice.\n<br><br><b>Equipamentos necessários:</b>\n<br>Superfície plana, antiderrapante, cones de marcação e trena de 20 metros para marca a distância entre os cones.\n<br><br><b>Vantagens:</b>\n<br>Grandes grupos podem realizar este teste de uma só vez. Além disso, o teste continua até o esforço máximo ao contrário de muitos outros testes de capacidade de resistência.\n<br><br><b>Desvantagens:</b>\n<br>O nível de prática e a motivação podem influenciar no resultado alcançado, e a pontuação pode ser subjetiva. O ensaio pode ser executado ao ar livre, e as condições ambientais podem afetar nos resultados.\n<br><br><b>Outras Considerações:</b>\n<br>Este teste pode ter muitos nomes, mas você precisa ter cuidado para que estes nomes diferentes não signifiquem que sejam outras versões diferentes do teste. Portanto, você precisa ter muito cuidado ao comparar os resultados deste teste com outros. Este teste é um teste máximo, o que exige um nível razoável de aptidão. Não é recomendado para atletas amadores ou pessoas com problemas de saúde, lesões ou baixos níveis de aptidão.\n</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbLink.setText("<html><p style=\"font-size: 11px;\"><b>Referências:</b></p><p style=\" text-align:justify;\"> Badminton Australia. National Junior Program Fitness Testing Protocols. Jan 2008. Disponível em:<br>  <a href=\"http://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CDIQFjAA&url=http%3A%2F%2Fwww.sportingpulse.com%2Fget_file.cgi%3Fid%3D256038&ei=n45cUba2HMPl0gHQsIDQDg&usg=AFQjCNHisJnaVZZrKSJhW1PHmHuBZV8Q-w&bvm=bv.44697112,d.dmQ \" target=_blank> http://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CDIQFjAA&url=%3Cbr%3Ehttp%3A%2F%2Fwww.sportingpulse.com%2Fget_file.cgi%3Fid%3D256038&ei=n45cU ba2H%3Cbr%3EMPl0gHQsIDQDg&usg=AFQjCNHisJnaVZZrKSJhW1PHmHuBZV8Q-w&bvm=bv.44697112,d.dmQ</a><br>  Acesso em : 04/07/2013.</p></html>");
        lbLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addComponent(lbLink, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLink, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLinkMouseClicked
        java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
        try{
            URI uri = new URI("http://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CDIQFjAA&url=http%3A%2F%2Fwww.sportingpulse.com%2Fget_"
                    + "file.cgi%3Fid%3D256038&ei=n45cUba2HMPl0gHQsIDQDg&usg=AFQjCNHisJnaVZZrKSJhW1PHmHuBZV8Q-w&bvm=bv.44697112,d.dmQ");
            desktop.browse(uri);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro: "+e.getMessage());
        }

    }//GEN-LAST:event_lbLinkMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lbLink;
    // End of variables declaration//GEN-END:variables
}
