/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

/**
 *
 * @author 5102011212
 */
public class ProtLancamentoDeBolasNaParede extends javax.swing.JPanel {

    /**
     * Creates new form ProtLancamentoDeBolasNaParede
     */
    public ProtLancamentoDeBolasNaParede() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLink = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamento de Bolas na Parede"));

        lbLink.setText("<html><p style=\"font-size: 11px;\"><b>Referências:</b></p><p style=\" text-align:justify;\">Topend Sports. Alternate Hand Wall Toss Test. Disponível em:<br>  <a href=\"http://www.topendsports.com/testing/tests/wall-catch.htm \" target=_blank>http://www.topendsports.com/testing/tests/wall-catch.htm </a><br>  Acesso em : 14/08/2013.</p></html>");
        lbLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setText("<html>\n<b>Equipamentos:</b>\n<br><br>Bola de tênis ou beisebol, parede lisa e sólida, fita de marcação, cronômetro (opcional).\n<br><br><b>Descrição:</b>\n<br><br>Uma marca é colocada a certa distância da parede (por exemplo, 2 metros, três pés). A pessoa que está por trás da linha e de frente para a parede lança a bola a partir de uma mão, na parede. E tenta pegar com a mão oposta a bola jogada. A bola é então jogada contra a parede e se pega com a mão inicial. O teste pode continuar por um número indicado de tentativas ou por um determinado período de tempo (por exemplo, 30 segundos). Ao adicionar a restrição de um determinado período de tempo, você também adicionar o fator de trabalhar sobre pressão.\n<br><br><b>Pontuação:</b>\n<br><br>A pontução é dada, com base no número de capturas de sucesso em um período de 30 segundos.\n</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(lbLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLink, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lbLink;
    // End of variables declaration//GEN-END:variables
}
