/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author 5102011212
 */
public class ProtAgilidadeEmQuadra extends javax.swing.JPanel {

    private String[] text = new String[3];//Array contendo o texto para setar no label text
    private int textIndex = 0;//número inteiro para setar o item do array text

    /**
     * Creates new form PAgilidadeEmQuadra
     */
    public ProtAgilidadeEmQuadra() {
        initComponents();
        setText();//adiciona os textos de cada posição do array text
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbResumo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbProtocolo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbReferencia = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder("Teste de agilidade em quadra"));

        lbResumo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbResumo, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbResumo, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Resumo", jPanel2);

        lbProtocolo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Protocolo", jPanel3);

        lbReferencia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbReferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbReferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReferenciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lbReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Referências", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbReferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReferenciaMouseClicked
        java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
        try {
            URI uri = new URI("http://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CDIQFjAA&url=http%3A%2F%2Fwww.sportingpulse.com%2Fget_"
                    + "file.cgi%3Fid%3D256038&ei=n45cUba2HMPl0gHQsIDQDg&usg=AFQjCNHisJnaVZZrKSJhW1PHmHuBZV8Q-w&bvm=bv.44697112,d.dmQ");
            desktop.browse(uri);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_lbReferenciaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbProtocolo;
    private javax.swing.JLabel lbReferencia;
    private javax.swing.JLabel lbResumo;
    // End of variables declaration//GEN-END:variables

    private void setText() {// adiciona todos os texto necessário para o array text
        text[0] = "<html> <br><b>Resumo:</b>"
                + " <br>Este é um teste bastante específico da modalidade em termos de deslocamento e necessidades fisiológicas."
                + " Este foi adaptado do teste de agilidade do Badminton England pelos AIS, mas a duração foi reduzida para ter"
                + " uma velocidade mais específica e representar melhor o tempo médio de duração de um rally (aproximadamente 6 segundos)."
                + " O teste do Badminton England leva em torno de 13 a 16 segundos, e então foi adaptado para reduzir essa duração."
                + " Isso contemplado reduzindo o numero de circuitos do teste para uma volta ao invés de duas por execução."
                + " A raquete pode ser substituída por outro equipamento se um aumento de precisão for necessário ao tocar as marcas. "
                + "<br><br><b>Equipamentos necessários:</b>"
                + " <br>Uma quadra de badminton com redes removidas,"
                + " raquete de badminton, fita acessiva, fita métrica, dois conjuntos sensores de passagem (preferencialmente) ou cronômetros,"
                + "10  tubo de peteca, 6 petecas <br><br><b>Preparação:</b> <br>Para preparar a quadra coloca os  equipamento descritos nas posições"
                + " descritas abaixo: <br>1- Marca um: Três tubos de peteca colados com fita devem ser colocados exatamente sobre a linha lateral "
                + "direita da quadra de simples, a 50 cm da linhada rede. <br>2- Marca dois: Uma peteca (com as penas para baixo) deve ser colocada"
                + " sobre a linha lateral direita da quadra de simples a 1,5 metros da linha de serviço. <br>3- Marca três: Uma peteca "
                + "(com as penas para baixo) deve ser colocada sobre dois tubos de peteca na linha lateral direita da quadra de simples"
                + " a 50 cm da linha de fundo. <br>4- Marca quatro: Três tubos de peteca colados com fita devem ser colocadas exatamente sobre"
                + " a linha lateral esquerda da quadra de simples, a 50 cm da linhada rede. <br>5- Marca cinco: Uma peteca (com as penas para baixo)"
                + " deve ser colocada sobre a linha lateral esquerda da quadra de simples a 1,5 metros da linha de serviço <br>6- Marca seis: "
                + "Uma peteca (com as penas para baixo) deve ser colocada sobre dois tubos de peteca na linha lateral esquerda da quadra"
                + " de simples a 50 cm da linha de fundo <br>7-Linha de Largada: deve ser posicionada sobre a linha de fundo e alinhada"
                + " ao centro da quadra com 1 metro de comprimento <br>8- Linha de Chegada: deve ser posicionada sobre a linha imaginária"
                + " da rede e alinhada ao centro da quadra com 1 metro de comprimento <br>9-Caixa de transição central: deve ser marcado"
                + " um retângulo  com 50X 75 cm iniciando ao 1,5 da linha de serviço e a alinhado horizontalmente no centro da quadra </html>";
        text[1] = "<html>\n"
                + "<br><b>Protocolo:</b>\n"
                + "<br>O indivíduo deve se mover através da linha de largada para a caixa de transição  antes de se deslocar para cada uma das marcas. O indivíduo precisa retornar ara caixa de transição antes de se mover para a próxima marca e antes de se mover para linha de chegada, depois tocar a ultima marca. O protocolo envolve movimentos e simulação de golpes específicos do badminton num conjunto de posições. O teste tem duração aproximada de 10 segundos. Deve se repetir três vezes com u m intervalo de descanso de no mínimo 2 minutos, sendo que o melhor tempo deve ser registrado. \n"
                + "Para iniciar o teste o indivíduo se posiciona em pé com seu pé de apoio imediatamente atrás da linha de largada. O teste começa quando ele quebra o feixe dos sensores de passagem ou quando o seu corpo atravessa a linha de largada, no caso de usar o cronômetro.\n"
                + "O teste se encerra quando ele quebra o feixe dos sensores de passagem ou quando o seu corpo através a linha de chegada, no caso de usar o cronômetro.\n"
                + "<br><br><u>Posição um:</u>\n"
                + "O Indivíduo precisa tocar o topo dos tubos de peteca com as cordas da raquete e retornar para a caixa de transição\n"
                + "<br><br><u>Posição dois:</u>\n"
                + "O Indivíduo precisa tirar a peteca da posição batendo com um golpe de forehand e retornar para caixa de transição.\n"
                + "<br><br><u>Posição três:</u>\n"
                + "O indivíduo precisa derrubar a peteca do topo dos tubos, batendo com um golpe de forehand e retornar para caixa de transição.\n"
                + "<br><br><u>Posição quatro:</u>\n"
                + "O Indivíduo precisa tocar o topo dos tubos de peteca com as cordas da raquete e retornar para a caixa de transição\n"
                + "<br><br><u>Posição cinco:</u>\n"
                + "O Indivíduo precisa tirar a peteca da posição batendo com um golpe de backhand e retornar para caixa de transição.\n"
                + "<br><br><u>Posição seis:</u>\n"
                + "O indivíduo precisa derrubar a peteca do topo dos tubos, batendo com um golpe de backhand e retornar para caixa de transição, antes de finalizar o teste passando pela linha de chegada.\n"
                + "<br><br><b>Regras:</b>\n"
                + "<br>1-uma corrida é considerada inválida se o indivíduo ganha vantagem por não colocar um pé na caixa de transição\n"
                + "<br>2-Esta configuração de quadra é baseada no indivíduo destro. Indivíduos canhotos devem executar os movimentos iniciando da esquerda para direita (4-5-6-1-2-3)\n"
                + "<br><br><b>O administrador do teste deve observar:</b>\n"
                + "<br>1-Se ouve o deslocamento da peteca ou se o indivíduo tocou o topo dos tubos com a raquete.\n"
                + "<br>2-se os tubos foram derrubados o teste só é considerado válido se ouve contato da raquete primeiramente com a peteca.\n"
                + "</html>";
        text[2] = "<html><p style=\"font-size: 11px;\"><b>Referências:</b></p>"
                + "<p style=\" text-align:justify;\"> Badminton Australia. National Junior Program Fitness Testing Protocols. Jan 2008. Disponível em:"
                + "<br>  <a href=\"http://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CDIQFjAA&url=http%3A%2F%2Fwww.sportingpulse."
                + "com%2Fget_file.cgi%3Fid%3D256038&ei=n45cUba2HMPl0gHQsIDQDg&usg=AFQjCNHisJnaVZZrKSJhW1PHmHuBZV8Q-w&bvm=bv.44697112,d.dmQ \" "
                + "target=_blank> http://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CDIQFjAA&url=%3Cbr%3Ehttp%3A%2F%2"
                + "<br>Fwww.sportingpulse."
                + "com%2Fget_file.cgi%3Fid%3D256038&ei=n45cU ba2H%3Cbr%3EMPl0gHQsIDQDg&usg=AFQjCNHisJnaVZZrKSJhW1PHmHuBZV8Q-w&bvm=bv.44697112,d.dmQ</a><br>  "
                + "Acesso em : 04/07/2013.</p></html>";
        this.lbResumo.setText(text[0]);
        this.lbProtocolo.setText(text[1]);
        this.lbReferencia.setText(text[2]);
    }
}
